name: Build

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14 * * 2" # 2pm Patch Tuesday

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build MariaDB"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
        name: Setup QEmu
      - uses: docker/setup-buildx-action@v1
        name: Setup Docker Buildx
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/login-action@v1
        name: Login to Github Container Registry
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        name: Build & Push
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            benzine/mariadb
            ghcr.io/benzine-framework/docker-mariadb
